---
title: "Monte Carlo integration"
output:
  pdf_document: default
  html_document: default
date: "2023-09-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(qrng)
library(random)
```

Vi testar integrera Nf(0,1) mellan -100,100 svaret bör vara runt ish 1. Vi gör det med monte carlo integration och vi jämför konvergenstiden mellan Pseudo-random variabler(det vanliga) och quasi-random(mer deterministiskt)

```{r}
set.seed(1)
n <- 10000
a <- -100 
b <- 100

f <- function(x){
  #return(x^2)
  return(1/sqrt(2*pi)*exp(-0.5*(x)^2)) #normalfördelningen
}

#Pseudo random vanliga
uPseudo <- runif(n,min = a,max = b) # OSU urval, kan testa olika
uPseudoSequential <-c()
estimatePseudo <- c()

#TrueRandom
#uTrue <-  a + (b-a) * randomNumbers(n = n, min = a*1000*(1/3), max = b*1000, col = 1)/100000
#uTrue[uTrue < 0 ]<- uTrue[uTrue < 0 ]* (1/3)
#uTrueSequential <- c()
#estimateTrue <- c()

#Quasi random
uSobol <- a + (b - a) * sobol(n)
uSobolSequential <-c()
estimateSobol <- c()


for (i in 1:n) {
  uPseudoSequential <- append(uPseudoSequential, uPseudo[i])
  uSobolSequential <- append(uSobolSequential, uSobol[i])
  
  #uTrue <- append(uTrueSequential, uTrue[i])

  resultPseudo <- (b - a) * mean(f(uPseudoSequential))
  resultSobol <- (b - a) * mean(f(uSobolSequential))
 
  #valid_uTrueSequential <- uTrueSequential[!is.na(uTrueSequential)]
  #resultTrue <- (b - a) * mean(f(valid_uTrueSequential))


  estimatePseudo <- append(estimatePseudo, resultPseudo)
  estimateSobol <- append(estimateSobol, resultSobol)
  
  #estimateTrue <- append(estimateTrue, resultTrue)
  
}


x <- seq(1,n)
plot(x,estimatePseudo, cex = 0.2, pch = 20, ylim = c(0.9,1.2), xlab = "n", ylab ="estimat", main = "Monte Carlo Integration av NF")
points(estimateSobol, col ="red", cex = 0.2, pch = 20)
#plot(x,estimateTrue, col ="blue", cex = 0.2, pch = 20,ylim = c(0.99,1.2),)
abline(h=1)
# Adding a legend
legend("topright", legend = c("Pseudo Random", "Quasi Random"), col = c("black", "red"), pch = 20, cex = 0.8)
cat("Pseudo-skattning:", resultPseudo, "\n")
cat("Quasi-skattning:", resultSobol, "\n")

```


```{r}
library(qrng)
set.seed(1)

n <- 10000
a <- -100 
b <- 100

f <- function(x){
  return(1/sqrt(2*pi)*exp(-0.5*(x)^2)) #normalfördelningen
}

#Pseudo 
uPseudo <- runif(n,min = a,max = b)

#Quasi 
uQuasi <-  a + (b - a) * sobol(n)


#skattningar
skattningPseudo <- (b-a) * mean(f(uPseudo))
skattningQuasi  <- (b-a) * mean(f(uQuasi))

cat("Pseudo-skattning:", skattningPseudo, "\n")
cat("Quasi-skattning:", skattningQuasi, "\n")
```
