# Funktion för 2dimensionell MC-integration

```{r}
mcInt2Dim <- function(nvalues, fxy, ax, ay, bx, by, RNG = c("Quasi", "Pseudo")){
  if (RNG == "Quasi"){
  x <- ax + (bx - ax) * sobol(nvalues, init = 123)
  y <- ay + (by - ay) * sobol(nvalues, init = 321)
  print(x[1:10])
  print(y[1:10])
  
  
  mean <- mean(fxy(x,y))
  estimate <-(bx-ax)*(by-ay)*mean
  return(estimate)
  }
  
  else if(RNG == "Pseudo"){
    x <- runif(nvalues, ax, bx)
    y <- runif(nvalues, ay, by)
    
    mean <- mean(fxy(x,y))
    estimate <-(bx-ax)*(by-ay)*mean
    return(estimate)
  }
}
```


# Exempel 

## Tvådimensionella funktioner

```{r}


fxy1 <- function(x,y){
  return(exp(x+y))
}

fxy2 <- function(x,y){
  return(x*y)
}

bivNF <- function(x, y, mu_x = 0, mu_y = 0, sigma_x = 1, sigma_y = 1){
  
  term1 <- 1 / (2 * pi * sigma_x * sigma_y)
  term2 <- -((x - mu_x)^2 / (2 * sigma_x^2) + (y - mu_y)^2 / (2 * sigma_y^2))
  return(term1 * exp(term2))
}
```

### beräkningar

```{r}
nvalues <- 1000
ax = 0
bx = 1
ay = 0
by = 1

cat("n:",nvalues,", ax:",ax,", bx:",bx,", ay:",ay, ", by:",by,"\n")

fxy1SolutionPseudo <- mcInt2Dim(nvalues, fxy1, ax, ay, bx, by, RNG = "Pseudo")
cat("Pseudoskattning:",fxy1SolutionPseudo,"\n")
fxy1SolutionQuasi <- mcInt2Dim(nvalues, fxy1, ax, ay, bx, by, RNG = "Quasi")
cat("Quasiskattning:",fxy1SolutionQuasi,"\n")

fxy2SolutionPseudo <- mcInt2Dim(nvalues, fxy2, ax, ay, bx, by, RNG = "Pseudo")
cat("Pseudoskattning:",fxy2SolutionPseudo,"\n")
fxy2SolutionQuasi <- mcInt2Dim(nvalues, fxy2, ax, ay, bx, by, RNG = "Quasi")
cat("Quasiskattning:",fxy2SolutionQuasi,"\n")

bivNFSolutionPseudo <- mcInt2Dim(nvalues, bivNF, ax, ay, bx, by, RNG = "Pseudo")
cat("Pseudoskattning:",bivNFSolutionPseudo,"\n")
bivNFSolutionQuasi <- mcInt2Dim(nvalues, bivNF, ax, ay, bx, by, RNG = "Quasi")
cat("Quasiskattning:",bivNFSolutionQuasi,"\n")
```





